### ISSUE TITLE
unable to hide application from menu

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-panels#2]
in v2 there was the ability to hide an app from the menu, so users wouldn't see it. 

I have 2 apps that need to be hidden from users' view in v3, but they're not hiding as they had in v2.

How can I make them launch with "autostart" - which is working - and keep them hidden from the menu?

**Comment by andersevenrud** [comment]
Added, documented and published :)

:+1: Thanks!

**Comment by andersevenrud** [comment]
The parameter is `hidden` btw.
