### ISSUE TITLE
Apply opacity only to the text and icon in unfocused windows

### ISSUE THREAD

**Issue by danielwaltz** [os-js/osjs-panels#21]
![os js bug](https://user-images.githubusercontent.com/161548/51433845-97bbab00-1c54-11e9-9738-6c4e8fd0144b.png)

_Originally posted by @andersevenrud in https://github.com/os-js/osjs-panels/pull/15#issuecomment-455861597_

**Comment by andersevenrud** [comment]
Did you want to fix this ? :)

**Comment by danielwaltz** [comment]
Yeah I was intending to, just been very busy at my job. Income gets top priority I'm afraid haha.

**Comment by andersevenrud** [comment]
This was fixed in https://github.com/os-js/osjs-standard-theme/commit/b1dc5d9ae94291a5f7a41c54da6b9206557c5f1a
