### ISSUE TITLE
allow functionality to show hide menus on right click on top menu 

### ISSUE THREAD

**Issue by Akshay99** [os-js/osjs-panels#23]
I am trying to hide menu right click that shows two option top and bottom client don't want to have that functionality and Osjs don't support any listener to manually inject any script.
It would be better to have flexibility to customise that settings on right click

**Comment by andersevenrud** [comment]
I've added a configuration option for this.

Run `npm update` to get latest published updates, then add the following setting to `src/client/config.js`:

```
{
  desktop: {
    disablePanelContextMenu: true
  }
}
```

and then finally rebuild with `npm run build`.

This will disable the context menus for all panels. I'm closing this issue, but please re-open if something does not work as expected.

**Comment by Akshay99** [comment]
Appreciate your help Thanks it works

**Comment by andersevenrud** [comment]
Glad to be of help!
