### ISSUE TITLE
Pinning applications to main menu

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-panels#29]
having ability to add applications to main menu in addition to categories.

---

Edited by @andersevenrud 

* [x] Pinning via static configuration
* [ ] Pinning via dynamic (user) configuration
    * [ ] Settings application ?
    * [ ] Custom dialog ?

**Comment by andersevenrud** [comment]
Technically this should work, but I'm not sure about the best way to make it possible.

Right now a false-y category will make it default to "other" :thinking:

**Comment by andersevenrud** [comment]
I've started working on a possible solution for this: https://github.com/os-js/osjs-panels/pull/31

What did you have in mind when enabling applications to show up on the root ?

1. Have it as a setting on the panel item (per application)
2. Have it as a setting on the client (per application)
3. Have it as a metadata entry

**Comment by msjavan** [comment]
3. Have it as a metadata entry.
For example if no category specified, goes to the root, or using an option to add favorite apps in the root.

**Comment by andersevenrud** [comment]
Here's the thing though. An application *should* define a category. It's not just for UI reasons.

As I said, it falls back to "other" when nothing is defined.

So I'm thinking option number 2:

```
{
  applications: {
    pinned: ['FileManager']
  }
}
```

**Comment by andersevenrud** [comment]
Or, seeing down the road option 1 might be best -- because then users can for example open a dialog (or the settings app) to set what apps they want to pin themselves. 

But this could be combined with 2 making it a global and per-user basis.

**Comment by msjavan** [comment]
I agree, It would be good to pin apps  per-user basis.

**Comment by andersevenrud** [comment]
I've implemented option 2.

I need to finish panel item settings persistence before being able to work in option 1.

**Comment by andersevenrud** [comment]
I've just published `@osjs/panels@3.0.21` that supports the following client option to pin applications globally:

```
{
  application: {
    pinned: ['FileManager']
  }
}
```

**Comment by andersevenrud** [comment]
@josephjeno You might have some use for this :)

**Comment by josephjeno** [comment]
@andersevenrud definitely!
