### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-panels#7]
I think that having a context menu on the panel that allows minimizing, maximizing, and closing items.

**Comment by andersevenrud** [comment]
Sure, that could be arranged.

Ref: https://github.com/os-js/osjs-panels/blob/master/src/items/windows.js

**Comment by SpaceboyRoss01** [comment]
I think we can close this now.

**Comment by andersevenrud** [comment]
Ah, yes.

This was fixed in https://github.com/os-js/osjs-panels/pull/8
